In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv("full_data.csv")
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [3]:
X

array([['Male', 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       ['Male', 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ['Female', 49.0, 0, ..., 171.23, 34.4, 'smokes'],
       ...,
       ['Female', 45.0, 1, ..., 95.02, 31.8, 'smokes'],
       ['Male', 40.0, 0, ..., 83.94, 30.0, 'smokes'],
       ['Female', 80.0, 1, ..., 83.75, 29.1, 'never smoked']],
      dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X[:, 4] = le.fit_transform(X[:, 4])
X[:, 6] = le.fit_transform(X[:, 6])

In [5]:
X

array([[1, 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       [1, 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       [0, 49.0, 0, ..., 171.23, 34.4, 'smokes'],
       ...,
       [0, 45.0, 1, ..., 95.02, 31.8, 'smokes'],
       [1, 40.0, 0, ..., 83.94, 30.0, 'smokes'],
       [0, 80.0, 1, ..., 83.75, 29.1, 'never smoked']], dtype=object)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5,9])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
X

array([[0.0, 1.0, 0.0, ..., 1, 228.69, 36.6],
       [0.0, 1.0, 0.0, ..., 0, 105.92, 32.5],
       [0.0, 1.0, 0.0, ..., 1, 171.23, 34.4],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 95.02, 31.8],
       [0.0, 1.0, 0.0, ..., 0, 83.94, 30.0],
       [0.0, 1.0, 0.0, ..., 1, 83.75, 29.1]], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [24]:
ann.fit(X_train, y_train, batch_size = 8, epochs = 50)

Epoch 1/50
498/498 [==============================] - 1s 895us/step - loss: 0.2232 - accuracy: 0.9506
Epoch 2/50
498/498 [==============================] - 0s 929us/step - loss: 0.1707 - accuracy: 0.9503
Epoch 3/50
498/498 [==============================] - 0s 900us/step - loss: 0.1661 - accuracy: 0.9503
Epoch 4/50
498/498 [==============================] - 0s 905us/step - loss: 0.1623 - accuracy: 0.9503
Epoch 5/50
498/498 [==============================] - 0s 917us/step - loss: 0.1599 - accuracy: 0.9503
Epoch 6/50
498/498 [==============================] - 0s 899us/step - loss: 0.1589 - accuracy: 0.9503
Epoch 7/50
498/498 [==============================] - 0s 913us/step - loss: 0.1573 - accuracy: 0.9503
Epoch 8/50
498/498 [==============================] - 0s 936us/step - loss: 0.1564 - accuracy: 0.9503
Epoch 9/50
498/498 [==============================] - 0s 889us/step - loss: 0.1551 - accuracy: 0.9508
Epoch 10/50
498/498 [==============================] - 0s 934us/step - loss: 0.154

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

32/32 [==============================] - 0s 775us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[946   1]
 [ 50   0]]


0.9488465396188566